[package]
name = "pathfinder"
version = "0.6.3"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.65"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pathfinder_lib"
path = "src/lib.rs"

[features]
tokio-console = ["console-subscriber", "tokio/tracing"]
rpc-full-serde = []
p2p = ["dep:p2p", "dep:p2p_proto"]

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1.59"
bitvec = "0.20.4"
casm-compiler-v1_0_0-alpha6 = { package = "cairo-lang-starknet", git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-alpha.6" }
casm-compiler-v1_0_0-rc0 = { package = "cairo-lang-starknet", git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-rc0" }
casm-compiler-v2_0_0-rc6 = { package = "cairo-lang-starknet", git = "https://github.com/starkware-libs/cairo", tag = "v2.0.0-rc6" }
clap = { workspace = true, features = ["derive", "env", "wrap_help"] }
console-subscriber = { version = "0.1.8", optional = true }
futures = { version = "0.3", default-features = false, features = ["std"] }
lazy_static = "1.4.0"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
p2p = { path = "../p2p", optional = true }
p2p_proto = { path = "../p2p_proto", optional = true }
pathfinder-common = { path = "../common" }
pathfinder-ethereum = { path = "../ethereum" }
pathfinder-merkle-tree = { path = "../merkle-tree" }
pathfinder-retry = { path = "../retry" }
pathfinder-rpc = { path = "../rpc" }
pathfinder-serde = { path = "../serde" }
pathfinder-storage = { path = "../storage" }
primitive-types = "0.12.1"
reqwest = { version = "0.11.13", features = ["json"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }
stark_hash = { path = "../stark_hash" }
starknet-gateway-client = { path = "../gateway-client" }
starknet-gateway-types = { path = "../gateway-types", features = ["test-utils"] }
tempfile = "3.4"
thiserror = "1.0.40"
time = { version = "0.3.20", features = ["macros"] }
tokio = { workspace = true, features = ["process"] }
toml = "0.5.9"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "time"] }
url = "2.3.1"
warp = "0.3.3"

[dev-dependencies]
assert_matches = { workspace = true }
bytes = "1.3.0"
const-decoder = "0.3.0"
criterion = "0.4"
fake = { version = "2.5.0", features = ["derive"] }
flate2 = "1.0.25"
http = "0.2.8"
mockall = "0.11.3"
p2p_proto = { path = "../p2p_proto", features = ["test-utils"] }
pathfinder-common = { path = "../common", features = ["full-serde", "test-utils"] }
pathfinder-rpc = { path = "../rpc", features = ["test-utils"] }
pathfinder-storage = { path = "../storage", features = ["test-utils"] }
pretty_assertions = "1.3.0"
proptest = "1.2.0"
rand = "0.8"
rand_chacha = "0.3.1"
rstest = "0.17.0"
serde_with = { workspace = true }
starknet-gateway-client = { path = "../gateway-client", features = ["test-utils"] }
starknet-gateway-test-fixtures = { path = "../gateway-test-fixtures" }
tokio = { workspace = true, features = ["test-util"] }
zstd = "0.12"

[build-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }
